name = "babaquinha"
main = "worker.js"
compatibility_date = "2024-12-15"

# Account ID can be found in Cloudflare dashboard
# account_id = "your-account-id"

# Workers configuration
workers_dev = true

[[kv_namespaces]]
binding = "babaquinha"
id = "30d867b39f0f46c6b337c19812abcd1"

[env.production]
name = "babaquinha-production"

[[env.production.kv_namespaces]]
binding = "babaquinha"
id = "30d867b39f0f46c6b337c19812abcd1"
